using Card_Game_Engine.Models.Enums;

namespace Card_Game_Engine.Models;

public class Constants
{
    public static readonly List<Card> DistinctCards = new List<Card>()
    {
        new Card(1, 1, SuitEnum.HEARTS),
        new Card(2, 2, SuitEnum.HEARTS),
        new Card(3, 3, SuitEnum.HEARTS),
        new Card(4, 4, SuitEnum.HEARTS),
        new Card(5, 5, SuitEnum.HEARTS),
        new Card(6, 6, SuitEnum.HEARTS),
        new Card(7, 7, SuitEnum.HEARTS),
        new Card(8, 8, SuitEnum.HEARTS),
        new Card(9, 9, SuitEnum.HEARTS),
        new Card(10, 10, SuitEnum.HEARTS),
        new Card(11, 11, SuitEnum.HEARTS),
        new Card(12, 12, SuitEnum.HEARTS),
        new Card(13, 13, SuitEnum.HEARTS),
        new Card(14, 1, SuitEnum.DIAMONDS),
        new Card(15, 2, SuitEnum.DIAMONDS),
        new Card(16, 3, SuitEnum.DIAMONDS),
        new Card(17, 4, SuitEnum.DIAMONDS),
        new Card(18, 5, SuitEnum.DIAMONDS),
        new Card(19, 6, SuitEnum.DIAMONDS),
        new Card(20, 7, SuitEnum.DIAMONDS),
        new Card(21, 8, SuitEnum.DIAMONDS),
        new Card(22, 9, SuitEnum.DIAMONDS),
        new Card(23, 10, SuitEnum.DIAMONDS),
        new Card(24, 11, SuitEnum.DIAMONDS),
        new Card(25, 12, SuitEnum.DIAMONDS),
        new Card(26, 13, SuitEnum.DIAMONDS),
        new Card(27, 1, SuitEnum.CLUBS),
        new Card(28, 2, SuitEnum.CLUBS),
        new Card(29, 3, SuitEnum.CLUBS),
        new Card(30, 4, SuitEnum.CLUBS),
        new Card(31, 5, SuitEnum.CLUBS),
        new Card(32, 6, SuitEnum.CLUBS),
        new Card(33, 7, SuitEnum.CLUBS),
        new Card(34, 8, SuitEnum.CLUBS),
        new Card(35, 9, SuitEnum.CLUBS),
        new Card(36, 10, SuitEnum.CLUBS),
        new Card(37, 11, SuitEnum.CLUBS),
        new Card(38, 12, SuitEnum.CLUBS),
        new Card(39, 13, SuitEnum.CLUBS),
        new Card(40, 1, SuitEnum.SPADES),
        new Card(41, 2, SuitEnum.SPADES),
        new Card(42, 3, SuitEnum.SPADES),
        new Card(43, 4, SuitEnum.SPADES),
        new Card(44, 5, SuitEnum.SPADES),
        new Card(45, 6, SuitEnum.SPADES),
        new Card(46, 7, SuitEnum.SPADES),
        new Card(47, 8, SuitEnum.SPADES),
        new Card(48, 9, SuitEnum.SPADES),
        new Card(49, 10, SuitEnum.SPADES),
        new Card(50, 11, SuitEnum.SPADES),
        new Card(51, 12, SuitEnum.SPADES),
        new Card(52, 13, SuitEnum.SPADES)
    };
}